apiVersion: apps/v1
kind: Deployment
metadata:
  name: language-translator-app-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: language-translator-app
  template:
    metadata:
      labels:
        app: language-translator-app
    spec:
      containers:
      - name: language-translator-app
        image: {{ .Values.image.repository }} # Use the latest language-translator-app image from Docker Hub
        ports:
        - containerPort: 8080 # The port on which the container is listening