apiVersion: v1
kind: Service
metadata:
  name: language-translator-app-svc
spec:
  type: LoadBalancer # Exposes the service externally using a cloud provider's load balancer
  ports:
  - port: 80 # The port that the service exposes
    targetPort: 8080 # The target port on the pod to forward to
  selector:
    app: language-translator-app # Selects the pods with the label "app: httpd"